name: 'Docker::Google Container Registry'
description: 'Push Docker image for Google Container Registry'
inputs:
  githubName:
    description: 'The name of the image on Github'
  gcrRegion:
    description: 'GCR region'
    required: true
  gcrProject:
    description: 'GCR project name'
    required: true
  gcrRepo:
    description: 'GCR repository name'
    required: true
  gcrJsonKey:
    description: 'Service account JSON key'
    required: true
  gcrName:
    description: 'Image name in GCR'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
