name: Build Docker Image

on:
  push:
    branches:
      - v*

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://ghcr.io/deeepvision/github-action-docker-build/docker-build:1.1
        with:
          name: github-action-docker-gcr
          registryType: ghcr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
